# Generated by Django 5.1.5 on 2025-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_address_account_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
