# Generated by Django 5.1.5 on 2025-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_city_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
