# Generated by Django 5.1.5 on 2025-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_city_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
