# Generated by Django 5.1.5 on 2025-03-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_address_line_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(max_length=50),
        ),
    ]
