# Generated by Django 5.1.5 on 2025-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_city_remove_account_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(max_length=50),
        ),
    ]
