# Generated by Django 5.1.5 on 2025-03-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_account_is_verified_account_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
