# Generated by Django 5.1.5 on 2025-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
